FROM python:3.10-slim

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . .

# Hugging Face Spaces bắt buộc app phải chạy ở Port 7860
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860"]